complete -c casspeed-cli -l help -d "Show help information"
complete -c casspeed-cli -l version -d "Show version information"
complete -c casspeed-cli -l server -d "Server URL"
complete -c casspeed-cli -l token -d "API token"
complete -c casspeed-cli -l output -d "Output format" -xa "text json table"
complete -c casspeed-cli -l debug -d "Enable debug output"
complete -c casspeed-cli -a test -d "Run speed test"
complete -c casspeed-cli -a history -d "Show test history"
complete -c casspeed-cli -a export -d "Export test data"
