complete -c casspeed -l help -d "Show help information"
complete -c casspeed -l version -d "Show version information"
complete -c casspeed -l mode -d "Application mode" -xa "production development"
complete -c casspeed -l config -d "Configuration directory" -xa "(__fish_complete_directories)"
complete -c casspeed -l data -d "Data directory" -xa "(__fish_complete_directories)"
complete -c casspeed -l cache -d "Cache directory" -xa "(__fish_complete_directories)"
complete -c casspeed -l log -d "Log directory" -xa "(__fish_complete_directories)"
complete -c casspeed -l backup -d "Backup directory" -xa "(__fish_complete_directories)"
complete -c casspeed -l pid -d "PID file path"
complete -c casspeed -l address -d "Listen address"
complete -c casspeed -l port -d "Listen port"
complete -c casspeed -l status -d "Show status and health"
complete -c casspeed -l service -d "Service management" -xa "start stop restart reload --install --uninstall --disable --help"
complete -c casspeed -l daemon -d "Daemonize (detach from terminal)"
complete -c casspeed -l debug -d "Enable debug mode"
complete -c casspeed -l maintenance -d "Maintenance operations" -xa "backup restore update mode setup"
complete -c casspeed -l update -d "Update operations" -xa "check yes branch"
